name: Deploy to remote server
on:
  push:
  branches:
    - main
 
jobs:
  deploy:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout code
    uses: actions/checkout@v2
   
  - name: Setup SSH Key
    uses: webfactory/ssh-agent@v0.5.0
    with:
    ssh-private-key: ${{ secrets.DEPLOY_KEY }}
   
  - name: Deploy code
    uses: appleboy/ssh-action@master
    with:
    host: your-remote-server.com
    username: your-ssh-username
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    script: |
      cd /var/www/my-app
      git pull origin main
      npm install
      npm run build
